// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-sites.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/helpers.ts
import { ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/helpers.ts
function requireClient(ctx) {
  if (!ctx.isAuthenticated()) {
    throw new ToolError("Not signed in. Connect this MCP server to your MiseOS account first.");
  }
  return supabaseForUser(ctx);
}
async function siteOrganisationId(client, siteId) {
  const { data, error } = await client.from("sites").select("organisation_id").eq("id", siteId).maybeSingle();
  if (error) throw new ToolError(error.message);
  if (!data) throw new ToolError("Site not found, or you do not have access to it.");
  return data.organisation_id;
}
function json(value) {
  return {
    content: [{ type: "text", text: JSON.stringify(value, null, 2) }]
  };
}

// src/lib/mcp/tools/list-sites.ts
var list_sites_default = defineTool({
  name: "list_sites",
  title: "List sites",
  description: "List the MiseOS sites (premises) the signed-in user can access, with premises type and operating mode.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const client = requireClient(ctx);
    const { data, error } = await client.from("sites").select("id, name, site_code, premises_type, operating_mode, timezone, active").eq("active", true).order("name");
    if (error) throw new ToolError2(error.message);
    return json({ sites: data ?? [] });
  }
});

// src/lib/mcp/tools/list-temperature-units.ts
import { defineTool as defineTool2, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_temperature_units_default = defineTool2({
  name: "list_temperature_units",
  title: "List temperature units",
  description: "List the fridges, freezers and other monitored units for a site, with their pass/fail temperature range.",
  inputSchema: { site_id: z.string().uuid().describe("Site id from list_sites.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ site_id }, ctx) => {
    const client = requireClient(ctx);
    const { data, error } = await client.from("temp_units").select("id, name, type, min_temp, max_temp, active").eq("site_id", site_id).eq("active", true).order("sort_order");
    if (error) throw new ToolError3(error.message);
    return json({ units: data ?? [] });
  }
});

// src/lib/mcp/tools/list-temperature-logs.ts
import { defineTool as defineTool3, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_temperature_logs_default = defineTool3({
  name: "list_temperature_logs",
  title: "List temperature logs",
  description: "List recent temperature readings for a site, newest first, including whether each reading passed.",
  inputSchema: {
    site_id: z2.string().uuid().describe("Site id from list_sites."),
    days: z2.number().int().optional().describe("How many days back to look. Defaults to 7, max 90."),
    only_failures: z2.boolean().optional().describe("Return only readings that failed.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ site_id, days, only_failures }, ctx) => {
    const client = requireClient(ctx);
    const window = Math.min(Math.max(days ?? 7, 1), 90);
    const since = new Date(Date.now() - window * 864e5).toISOString();
    let query = client.from("temp_logs").select("id, unit_id, log_type, value, pass, food_item, corrective_action, logged_at, logged_by_name").eq("site_id", site_id).gte("logged_at", since).order("logged_at", { ascending: false }).limit(200);
    if (only_failures) query = query.eq("pass", false);
    const { data, error } = await query;
    if (error) throw new ToolError4(error.message);
    return json({ days: window, logs: data ?? [] });
  }
});

// src/lib/mcp/tools/log-temperature.ts
import { defineTool as defineTool4, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var log_temperature_default = defineTool4({
  name: "log_temperature",
  title: "Log a temperature reading",
  description: "Record a temperature reading for a site. Pass/fail is derived from the unit's range when a unit_id is given.",
  inputSchema: {
    site_id: z3.string().uuid().describe("Site id from list_sites."),
    value: z3.number().describe("Temperature in degrees Celsius."),
    unit_id: z3.string().uuid().optional().describe("Monitored unit id from list_temperature_units."),
    log_type: z3.string().optional().describe("Reading type, e.g. unit, cooking, reheating, hot_holding, cooling, delivery."),
    food_item: z3.string().optional().describe("Food item the reading relates to, for process checks."),
    corrective_action: z3.string().optional().describe("Action taken if the reading failed."),
    logged_by_name: z3.string().optional().describe("Who took the reading. Defaults to the signed-in user.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const client = requireClient(ctx);
    const organisation_id = await siteOrganisationId(client, input.site_id);
    let pass = true;
    if (input.unit_id) {
      const { data: unit, error: unitError } = await client.from("temp_units").select("min_temp, max_temp").eq("id", input.unit_id).eq("site_id", input.site_id).maybeSingle();
      if (unitError) throw new ToolError5(unitError.message);
      if (!unit) throw new ToolError5("Unit not found for this site.");
      pass = input.value >= Number(unit.min_temp) && input.value <= Number(unit.max_temp);
    }
    const { data, error } = await client.from("temp_logs").insert({
      site_id: input.site_id,
      organisation_id,
      unit_id: input.unit_id ?? null,
      log_type: input.log_type ?? (input.unit_id ? "unit" : "process"),
      value: input.value,
      pass,
      food_item: input.food_item ?? null,
      corrective_action: input.corrective_action ?? null,
      logged_by_name: input.logged_by_name ?? ctx.getUserEmail() ?? "MCP",
      logged_by_user_id: ctx.getUserId() ?? null
    }).select("id, value, pass, log_type, logged_at").single();
    if (error) throw new ToolError5(error.message);
    return json({ reading: data });
  }
});

// src/lib/mcp/tools/list-incidents.ts
import { defineTool as defineTool5, ToolError as ToolError6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_incidents_default = defineTool5({
  name: "list_incidents",
  title: "List incidents",
  description: "List food safety incidents and non-conformances for a site, newest first.",
  inputSchema: {
    site_id: z4.string().uuid().describe("Site id from list_sites."),
    status: z4.string().optional().describe("Filter by status, e.g. open or closed.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ site_id, status }, ctx) => {
    const client = requireClient(ctx);
    let query = client.from("incidents").select("id, title, type, status, description, immediate_action, root_cause, prevention, reported_at, reported_by_name").eq("site_id", site_id).order("reported_at", { ascending: false }).limit(100);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) throw new ToolError6(error.message);
    return json({ incidents: data ?? [] });
  }
});

// src/lib/mcp/tools/create-incident.ts
import { defineTool as defineTool6, ToolError as ToolError7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var create_incident_default = defineTool6({
  name: "create_incident",
  title: "Report an incident",
  description: "Report a food safety incident or non-conformance for a site. Creates an open incident record.",
  inputSchema: {
    site_id: z5.string().uuid().describe("Site id from list_sites."),
    title: z5.string().describe("Short summary of what happened."),
    description: z5.string().describe("What happened, in detail."),
    immediate_action: z5.string().describe("What was done straight away to make things safe."),
    type: z5.string().optional().describe("Incident type, e.g. temperature, pest, allergen, equipment, other."),
    root_cause: z5.string().optional().describe("Root cause, if already known."),
    prevention: z5.string().optional().describe("How a repeat will be prevented.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const client = requireClient(ctx);
    const organisation_id = await siteOrganisationId(client, input.site_id);
    const { data, error } = await client.from("incidents").insert({
      site_id: input.site_id,
      organisation_id,
      title: input.title,
      description: input.description,
      immediate_action: input.immediate_action,
      type: input.type ?? "other",
      root_cause: input.root_cause ?? null,
      prevention: input.prevention ?? null,
      status: "open",
      reported_by_name: ctx.getUserEmail() ?? "MCP",
      reported_by_user_id: ctx.getUserId() ?? null
    }).select("id, title, type, status, reported_at").single();
    if (error) throw new ToolError7(error.message);
    return json({ incident: data });
  }
});

// src/lib/mcp/tools/list-batches.ts
import { defineTool as defineTool7, ToolError as ToolError8 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_batches_default = defineTool7({
  name: "list_batches",
  title: "List production batches",
  description: "List recent production batches for a site, newest first, with batch code, product, quantity and use-by date.",
  inputSchema: {
    site_id: z6.string().uuid().describe("Site id from list_sites."),
    days: z6.number().int().optional().describe("How many days back to look. Defaults to 14, max 180.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ site_id, days }, ctx) => {
    const client = requireClient(ctx);
    const window = Math.min(Math.max(days ?? 14, 1), 180);
    const since = new Date(Date.now() - window * 864e5).toISOString();
    const { data, error } = await client.from("batches").select("id, batch_code, product_name, quantity_produced, quantity_unit, status, date_produced, use_by_date, created_at").eq("site_id", site_id).gte("created_at", since).order("created_at", { ascending: false }).limit(100);
    if (error) throw new ToolError8(error.message);
    return json({ days: window, batches: data ?? [] });
  }
});

// src/lib/mcp/index.ts
var projectRef = "elcmnvgbmzusogudpenp";
var mcp_default = defineMcp({
  name: "miseos",
  title: "MiseOS",
  version: "0.1.0",
  instructions: "Food safety and HACCP tools for MiseOS. Start with `list_sites` to get a site id, then read or record temperature checks, incidents and production batches for that site. All tools act as the signed-in MiseOS user and respect their site access.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_sites_default,
    list_temperature_units_default,
    list_temperature_logs_default,
    log_temperature_default,
    list_incidents_default,
    create_incident_default,
    list_batches_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
